openapi: 3.0.0
info:
  title: Digital Citizenship Admin API.
  description: Digital Citizenship Admin API.
  version: 0.1.0
servers:
- url: ///adm
security:
- SubscriptionKey: []
paths:
  /services/{service_id}:
    get:
      summary: Get Service
      description: A previously created service with the provided service ID is returned.
      operationId: getService
      parameters:
      - name: service_id
        in: path
        description: The ID of an existing Service.
        required: true
        schema:
          type: string
      responses:
        200:
          description: Service found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
              example:
                id: 2b3e728c1a5d1efa035c-0000000000000001
                authorized_recipients:
                - XXXYYY79A95Y000X
                department_name: dept
                organization_name: org
                service_id: 2b3e728c1a5d1efa035c
                service_name: service
                version: 1
                authorized_cidrs: []
        401:
          description: Unauthorized
          content: {}
        404:
          description: No service found for the provided ID.
          content: {}
    put:
      summary: Update Service
      description: |-
        Update an existing service with the attributes provided in the
        request payload.
      operationId: updateService
      parameters:
      - name: service_id
        in: path
        description: The ID of an existing Service.
        required: true
        schema:
          type: string
      requestBody:
        description: The Service payload.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service'
        required: false
      responses:
        200:
          description: Service updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
              example:
                id: 2b3e728c1a5d1efa035c-0000000000000001
                authorized_recipients:
                - XXXYYY79A95Y000X
                department_name: dept
                organization_name: org
                service_id: 2b3e728c1a5d1efa035c
                service_name: service
                version: 1
                authorized_cidrs: []
        401:
          description: Unauthorized
          content: {}
        404:
          description: No service found for the provided ID.
          content: {}
  /debug:
    get:
      summary: Debug GET
      description: An endpoint to debug GET requests to the API backend.
      operationId: getDebug
      responses:
        200:
          description: |-
            Returns a JSON object with HTTP request parameters, headers
            and payload.
          content:
            application/json:
              schema:
                type: object
              example:
                auth:
                  groups:
                  - ApiInfoRead
                  - ApiMessageRead
                  - ApiLimitedMessageWrite
                  - ApiDebugRead
                  kind: IAzureApiAuthorization
                  subscriptionId: 9d39a48a64370b1b326dfb70307008
                  userId: 9d39a48a64370b1b326dfb70307008
                headers:
                  cache-control: no-cache
                  connection: Keep-Alive
                  accept: application/json
                  accept-encoding: gzip, deflate
                  max-forwards: "10"
                  user-agent: PostmanRuntime/6.4.1
                  ocp-apim-subscription-key: d5310672bc1d8cf383ca98
                  x-user-id: 9d39a48a64370b1b326dfb70307008
                  x-user-groups: Developers,ApiInfoRead,ApiMessageRead,ApiLimitedMessageWrite,ApiDebugRead
                  x-subscription-id: 9d39a48a64370b1b326dfb70307008
                  x-user-email: example@example.com
                  x-functions-key: 9d39a48a64370b1b326dfb70307008
                  x-forwarded-for: 111.97.111.36, 111.40.111.45:1088
                  x-waws-unencoded-url: /adm/debug
                  x-original-url: /adm/debug
                  x-arr-log-id: 9d39a48-a64370b-1b326dfb703-07008
                  x-forwarded-proto: https
                  content-type: application/json
                  content-length: "0"
                params: {}
                user:
                  email: example@example.com
                  kind: IAzureUserAttributes
                  service:
                    authorized_recipients:
                    - XXXBEN86A11Y755X
                    department_name: dept
                    organization_name: org
                    service_id: 9d39a48a64370b1b326dfb70307008
                    service_name: service
                    id: 9d39a48a64370b1b326dfb70307008-0000000000000000
                    version: 0
                    authorized_cidrs: []
                    kind: IRetrievedService
        401:
          description: Unauthorized
          content: {}
    post:
      summary: Debug POST
      description: An endpoint to debug POST requests to the API backend.
      operationId: postDebug
      responses:
        200:
          description: |-
            Returns a JSON object with HTTP request parameters, headers
            and payload.
          content:
            application/json:
              schema:
                type: object
              example:
                auth:
                  groups:
                  - ApiInfoRead
                  - ApiMessageRead
                  - ApiLimitedMessageWrite
                  - ApiDebugRead
                  kind: IAzureApiAuthorization
                  subscriptionId: 9d39a48a64370b1b326dfb70307008
                  userId: 9d39a48a64370b1b326dfb70307008
                headers:
                  cache-control: no-cache
                  connection: Keep-Alive
                  accept: application/json
                  accept-encoding: gzip, deflate
                  max-forwards: "10"
                  user-agent: PostmanRuntime/6.4.1
                  ocp-apim-subscription-key: d5310672bc1d8cf383ca98
                  x-user-id: 9d39a48a64370b1b326dfb70307008
                  x-user-groups: Developers,ApiInfoRead,ApiMessageRead,ApiLimitedMessageWrite,ApiDebugRead
                  x-subscription-id: 9d39a48a64370b1b326dfb70307008
                  x-user-email: example@example.com
                  x-functions-key: 9d39a48a64370b1b326dfb70307008
                  x-forwarded-for: 111.97.111.36, 111.40.111.45:1088
                  x-waws-unencoded-url: /adm/debug
                  x-original-url: /adm/debug
                  x-arr-log-id: 9d39a48-a64370b-1b326dfb703-07008
                  x-forwarded-proto: https
                  content-type: application/json
                  content-length: "0"
                params: {}
                user:
                  email: example@example.com
                  kind: IAzureUserAttributes
                  service:
                    authorized_recipients:
                    - XXXBEN86A11Y755X
                    department_name: dept
                    organization_name: org
                    service_id: 9d39a48a64370b1b326dfb70307008
                    service_name: service
                    id: 9d39a48a64370b1b326dfb70307008-0000000000000000
                    version: 0
                    authorized_cidrs: []
                    kind: IRetrievedService
        401:
          description: Unauthorized
          content: {}
  /services:
    post:
      summary: Create Service
      description: |-
        Create a new Service with the attributes provided in the requst
        payload.
      operationId: createService
      requestBody:
        description: The Service payload.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service'
        required: false
      responses:
        200:
          description: Service created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
              example:
                id: 2b3e728c1a5d1efa035c-0000000000000001
                authorized_recipients:
                - XXXYYY79A95Y000X
                department_name: dept
                organization_name: org
                service_id: 2b3e728c1a5d1efa035c
                service_name: service
                version: 1
                authorized_cidrs: []
        401:
          description: Unauthorized
          content: {}
components:
  schemas:
    Service:
      $ref: '#/components/schemas/Service'
  securitySchemes:
    SubscriptionKey:
      type: apiKey
      description: The API key obtained through the developer portal.
      name: Ocp-Apim-Subscription-Key
      in: header
